"""Knowledge vault service implementing an Obsidian-compatible local wiki workflow."""
from __future__ import annotations

import io
import json
import re
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from uuid import uuid4

import yaml
from pypdf import PdfReader

from backend.config import settings
from backend.llm import get_llm
from backend.models.knowledge import (
    KnowledgeIngestResult,
    KnowledgePage,
    KnowledgePageDetail,
    KnowledgeSource,
    KnowledgeStatus,
)
from backend.services import notes_service

VAULT_STRUCTURE = [
    "raw/notes",
    "raw/uploads",
    "raw/extracted",
    "wiki/entities",
    "wiki/concepts",
    "wiki/sources",
    "wiki/analyses",
]
RESERVED_WIKI_FILES = {"index.md", "log.md"}
ALLOWED_ROOTS = {"entities", "concepts", "sources", "analyses"}
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")
TOKEN_RE = re.compile(r"[A-Za-z0-9_]+")
WRITESET_RE = re.compile(r"```json\s*(\{.*?\})\s*```", re.DOTALL)

_operation_lock = threading.Lock()

AGENTS_TEMPLATE = """# Knowledge Vault Contract

This vault is the canonical knowledge base and is intentionally Obsidian-compatible.

## Page types
- overview
- entity
- concept
- source
- analysis

## Frontmatter contract
All wiki pages must include YAML frontmatter fields:
- type
- title
- summary
- updated_at
- source_ids
- tags
- aliases

## Body contract
- Use Obsidian wikilinks for cross references: [[Page Name]].
- Keep pages concise and factual.
- Source pages should point back to immutable entries under raw/.

## System-managed files
- `wiki/index.md` is generated deterministically by the app.
- `wiki/log.md` is append-only and generated by the app.
"""


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _iso_now() -> str:
    return _utcnow().isoformat()


def _vault_path() -> Path:
    return Path(settings.knowledge_vault_path)


def _wiki_root() -> Path:
    return _vault_path() / "wiki"


def _safe_relative(base: Path, candidate: Path) -> Path:
    """Resolve a path and ensure it stays under base."""
    resolved_base = base.resolve()
    resolved_candidate = candidate.resolve()
    try:
        resolved_candidate.relative_to(resolved_base)
    except ValueError as exc:
        raise ValueError(f"Unsafe path outside vault: {candidate}") from exc
    return resolved_candidate


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_name(f"{path.name}.tmp-{uuid4().hex}")
    temp_path.write_text(content, encoding="utf-8")
    temp_path.replace(path)


def _normalize_list(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    if isinstance(value, str):
        return [part.strip() for part in value.split(",") if part.strip()]
    return []


def _sanitize_slug(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip().lower())
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-")
    return normalized or uuid4().hex[:8]


def _frontmatter_to_text(frontmatter: dict[str, Any], body: str) -> str:
    yaml_block = yaml.safe_dump(frontmatter, allow_unicode=False, sort_keys=True).strip()
    return f"---\n{yaml_block}\n---\n\n{body.strip()}\n"


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text.strip()
    raw = match.group(1)
    metadata = yaml.safe_load(raw) or {}
    body = text[match.end():].strip()
    return metadata, body


def extract_wikilinks(body: str) -> list[str]:
    links: list[str] = []
    seen: set[str] = set()
    for match in WIKILINK_RE.finditer(body):
        link = match.group(1).strip()
        if not link:
            continue
        if link.lower() in seen:
            continue
        seen.add(link.lower())
        links.append(link)
    return links


def ensure_vault_initialized() -> None:
    vault = _vault_path()
    vault.mkdir(parents=True, exist_ok=True)

    for relative in VAULT_STRUCTURE:
        (vault / relative).mkdir(parents=True, exist_ok=True)

    agents_file = vault / "AGENTS.md"
    if not agents_file.exists():
        _atomic_write(agents_file, AGENTS_TEMPLATE)

    overview = _wiki_root() / "overview.md"
    if not overview.exists():
        content = _frontmatter_to_text(
            {
                "type": "overview",
                "title": "Knowledge Overview",
                "summary": "Top-level summary page for the local knowledge vault.",
                "updated_at": _iso_now(),
                "source_ids": [],
                "tags": ["overview"],
                "aliases": ["Vault Overview"],
            },
            "This page summarizes the local knowledge base.\n",
        )
        _atomic_write(overview, content)

    index_file = _wiki_root() / "index.md"
    if not index_file.exists():
        _atomic_write(index_file, "# Knowledge Index\n\n")

    log_file = _wiki_root() / "log.md"
    if not log_file.exists():
        _atomic_write(log_file, "# Knowledge Log\n\n")


def _page_from_file(path: Path) -> KnowledgePage:
    raw = path.read_text(encoding="utf-8")
    metadata, _ = parse_frontmatter(raw)
    rel = path.resolve().relative_to(_wiki_root().resolve()).as_posix()
    return KnowledgePage(
        path=rel,
        type=str(metadata.get("type", "unknown")),
        title=str(metadata.get("title", path.stem)),
        summary=str(metadata.get("summary", "")),
        updated_at=str(metadata.get("updated_at", "")),
        source_ids=_normalize_list(metadata.get("source_ids")),
        tags=_normalize_list(metadata.get("tags")),
        aliases=_normalize_list(metadata.get("aliases")),
    )


def _iter_wiki_pages() -> list[Path]:
    pages: list[Path] = []
    for file in _wiki_root().rglob("*.md"):
        if file.name in RESERVED_WIKI_FILES:
            continue
        pages.append(file)
    return sorted(pages)


def rebuild_index() -> str:
    ensure_vault_initialized()
    pages = [_page_from_file(path) for path in _iter_wiki_pages()]
    pages.sort(key=lambda page: page.path)

    lines = [
        "# Knowledge Index",
        "",
        "_Generated deterministically from wiki page frontmatter._",
        "",
        "| Path | Type | Title | Summary | Tags | Aliases | Updated At |",
        "|---|---|---|---|---|---|---|",
    ]
    for page in pages:
        tags = ", ".join(page.tags)
        aliases = ", ".join(page.aliases)
        summary = page.summary.replace("|", "/")
        title = page.title.replace("|", "/")
        lines.append(
            f"| {page.path} | {page.page_type} | {title} | {summary} | {tags} | {aliases} | {page.updated_at} |"
        )
    content = "\n".join(lines).strip() + "\n"
    _atomic_write(_wiki_root() / "index.md", content)
    return content


def _parse_index_rows(index_text: str) -> list[KnowledgePage]:
    rows: list[KnowledgePage] = []
    for line in index_text.splitlines():
        if not line.startswith("|"):
            continue
        if line.startswith("|---") or "Path" in line:
            continue
        parts = [part.strip() for part in line.split("|")[1:-1]]
        if len(parts) < 7:
            continue
        path, page_type, title, summary, tags, aliases, updated_at = parts[:7]
        rows.append(
            KnowledgePage(
                path=path,
                type=page_type,
                title=title,
                summary=summary,
                updated_at=updated_at,
                source_ids=[],
                tags=_normalize_list(tags),
                aliases=_normalize_list(aliases),
            )
        )
    return rows


def _index_text() -> str:
    ensure_vault_initialized()
    index_file = _wiki_root() / "index.md"
    if not index_file.exists():
        return rebuild_index()
    return index_file.read_text(encoding="utf-8")


def _log_path() -> Path:
    return _wiki_root() / "log.md"


def append_log(operation: str, target: str) -> str:
    entry = f"## [{_iso_now()}] {operation} | {target}"
    log_file = _log_path()
    content = log_file.read_text(encoding="utf-8")
    content = content.rstrip() + "\n\n" + entry + "\n"
    _atomic_write(log_file, content)
    return entry


def _last_log_entry() -> str | None:
    lines = _log_path().read_text(encoding="utf-8").splitlines()
    for line in reversed(lines):
        if line.startswith("## ["):
            return line
    return None


def _tokenize(value: str) -> set[str]:
    return {token.lower() for token in TOKEN_RE.findall(value or "") if token}


def _score_page(page: KnowledgePage, query_tokens: set[str]) -> float:
    haystack = " ".join([page.title, page.summary, " ".join(page.tags), " ".join(page.aliases)])
    page_tokens = _tokenize(haystack)
    if not page_tokens:
        return 0.0
    overlap = len(query_tokens & page_tokens)
    if overlap == 0:
        return 0.0
    return overlap / max(len(query_tokens), 1)


def list_pages(page_type: str | None = None, q: str | None = None) -> list[KnowledgePage]:
    index_rows = _parse_index_rows(_index_text())
    if not index_rows:
        rebuild_index()
        index_rows = _parse_index_rows(_index_text())

    filtered = index_rows
    if page_type:
        target = page_type.strip().lower()
        filtered = [page for page in filtered if page.page_type == target]

    if q and q.strip():
        query_tokens = _tokenize(q)
        scored: list[KnowledgePage] = []
        for page in filtered:
            score = _score_page(page, query_tokens)
            if score > 0:
                scored.append(page.model_copy(update={"score": score}))
        scored.sort(key=lambda page: (page.score or 0, page.updated_at, page.path), reverse=True)
        return scored

    return sorted(filtered, key=lambda page: (page.updated_at, page.path), reverse=True)


def search_pages(query: str, page_type: str | None = None, limit: int = 5) -> list[KnowledgePage]:
    pages = list_pages(page_type=page_type, q=query)
    return pages[: max(1, min(limit, 25))]


def _resolve_wiki_page_path(path: str) -> Path:
    if not path:
        raise ValueError("Page path is required")
    normalized = path.strip().replace("\\", "/")
    if normalized.startswith("wiki/"):
        normalized = normalized[5:]
    if normalized.startswith("/"):
        normalized = normalized[1:]
    if not normalized.endswith(".md"):
        normalized += ".md"
    candidate = _wiki_root() / normalized
    safe = _safe_relative(_wiki_root(), candidate)
    if safe.name in RESERVED_WIKI_FILES:
        raise ValueError("Reserved page path")
    return safe


def get_page(path: str) -> KnowledgePageDetail:
    ensure_vault_initialized()
    page_file = _resolve_wiki_page_path(path)
    if not page_file.exists():
        raise FileNotFoundError(path)
    raw = page_file.read_text(encoding="utf-8")
    metadata, body = parse_frontmatter(raw)
    rel = page_file.resolve().relative_to(_wiki_root().resolve()).as_posix()
    return KnowledgePageDetail(
        path=rel,
        type=str(metadata.get("type", "unknown")),
        title=str(metadata.get("title", page_file.stem)),
        summary=str(metadata.get("summary", "")),
        updated_at=str(metadata.get("updated_at", "")),
        source_ids=_normalize_list(metadata.get("source_ids")),
        tags=_normalize_list(metadata.get("tags")),
        aliases=_normalize_list(metadata.get("aliases")),
        body=body,
        wikilinks=extract_wikilinks(body),
    )


def _source_from_markdown(path: Path) -> KnowledgeSource | None:
    if not path.exists():
        return None
    metadata, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
    source_id = str(metadata.get("source_id", "")).strip()
    kind = str(metadata.get("source_kind", "")).strip()
    if not source_id or kind not in {"note", "file"}:
        return None
    raw_path = path.resolve().relative_to(_vault_path().resolve()).as_posix()
    extracted_path = metadata.get("extracted_path")
    return KnowledgeSource(
        source_id=source_id,
        kind=kind,
        title=str(metadata.get("title", source_id)),
        created_at=str(metadata.get("created_at", "")),
        raw_path=raw_path,
        extracted_path=str(extracted_path) if extracted_path else None,
        note_id=str(metadata.get("note_id")) if metadata.get("note_id") else None,
        original_filename=str(metadata.get("original_filename")) if metadata.get("original_filename") else None,
    )


def list_sources() -> list[KnowledgeSource]:
    ensure_vault_initialized()
    sources: list[KnowledgeSource] = []

    for file in (_vault_path() / "raw" / "notes").glob("*.md"):
        source = _source_from_markdown(file)
        if source:
            sources.append(source)

    for file in (_vault_path() / "raw" / "extracted").glob("*.md"):
        source = _source_from_markdown(file)
        if source:
            sources.append(source)

    sources.sort(key=lambda item: item.created_at, reverse=True)
    return sources


def get_status() -> KnowledgeStatus:
    ensure_vault_initialized()
    return KnowledgeStatus(
        vault_path=str(_vault_path()),
        initialized=True,
        page_count=len(list_pages()),
        source_count=len(list_sources()),
        last_log_entry=_last_log_entry(),
    )


def _source_page_markdown(source: KnowledgeSource) -> str:
    rel_raw = source.raw_path
    rel_extracted = source.extracted_path or ""
    body = [
        f"Source `{source.source_id}` captured from `{source.kind}` input.",
        "",
        f"- Raw: `{rel_raw}`",
    ]
    if rel_extracted:
        body.append(f"- Extracted: `{rel_extracted}`")
    if source.note_id:
        body.append(f"- Note ID: `{source.note_id}`")
    if source.original_filename:
        body.append(f"- Original filename: `{source.original_filename}`")
    return _frontmatter_to_text(
        {
            "type": "source",
            "title": source.title,
            "summary": f"Source snapshot {source.source_id}",
            "updated_at": _iso_now(),
            "source_ids": [source.source_id],
            "tags": ["source", source.kind],
            "aliases": [source.source_id],
        },
        "\n".join(body),
    )


def _snapshot_note(note_id: str) -> tuple[KnowledgeSource, str]:
    note = notes_service.get_note(note_id)
    if not note:
        raise FileNotFoundError(note_id)

    source_id = f"note-{_utcnow().strftime('%Y%m%d%H%M%S')}-{uuid4().hex[:8]}"
    filename = f"{source_id}.md"
    path = _vault_path() / "raw" / "notes" / filename
    tags = note.get("tags", [])
    content_body = str(note.get("content", "")).strip()
    title = str(note.get("title", "Untitled Note")).strip() or "Untitled Note"
    markdown = _frontmatter_to_text(
        {
            "source_id": source_id,
            "source_kind": "note",
            "note_id": note_id,
            "title": title,
            "tags": tags,
            "created_at": _iso_now(),
        },
        content_body,
    )
    _atomic_write(path, markdown)

    source = KnowledgeSource(
        source_id=source_id,
        kind="note",
        title=title,
        created_at=_iso_now(),
        raw_path=path.resolve().relative_to(_vault_path().resolve()).as_posix(),
        extracted_path=None,
        note_id=note_id,
    )
    return source, content_body


def _extract_pdf_text(data: bytes) -> str:
    reader = PdfReader(io.BytesIO(data))
    chunks: list[str] = []
    for page in reader.pages:
        text = page.extract_text() or ""
        if text.strip():
            chunks.append(text.strip())
    return "\n\n".join(chunks).strip()


def ingest_file_bytes(filename: str, data: bytes) -> tuple[KnowledgeSource, str]:
    ensure_vault_initialized()
    suffix = Path(filename).suffix.lower()
    if suffix not in {".md", ".txt", ".pdf"}:
        raise ValueError("Unsupported file type. Only .md, .txt, and .pdf are allowed.")

    source_id = f"file-{_utcnow().strftime('%Y%m%d%H%M%S')}-{uuid4().hex[:8]}"
    upload_name = f"{source_id}{suffix}"
    upload_path = _vault_path() / "raw" / "uploads" / upload_name
    upload_path.parent.mkdir(parents=True, exist_ok=True)
    upload_path.write_bytes(data)

    if suffix == ".pdf":
        extracted_text = _extract_pdf_text(data)
    else:
        extracted_text = data.decode("utf-8", errors="ignore").strip()

    if not extracted_text:
        extracted_text = "(No extractable text found in source.)"

    extracted_filename = f"{source_id}.md"
    extracted_path = _vault_path() / "raw" / "extracted" / extracted_filename
    extracted_markdown = _frontmatter_to_text(
        {
            "source_id": source_id,
            "source_kind": "file",
            "title": filename,
            "original_filename": filename,
            "created_at": _iso_now(),
            "extracted_path": extracted_path.resolve().relative_to(_vault_path().resolve()).as_posix(),
        },
        extracted_text,
    )
    _atomic_write(extracted_path, extracted_markdown)

    source = KnowledgeSource(
        source_id=source_id,
        kind="file",
        title=filename,
        created_at=_iso_now(),
        raw_path=upload_path.resolve().relative_to(_vault_path().resolve()).as_posix(),
        extracted_path=extracted_path.resolve().relative_to(_vault_path().resolve()).as_posix(),
        original_filename=filename,
    )
    return source, extracted_text


def _normalize_write_path(path: str) -> str:
    cleaned = path.strip().replace("\\", "/")
    if cleaned.startswith("wiki/"):
        cleaned = cleaned[5:]
    if cleaned.startswith("/"):
        cleaned = cleaned[1:]
    if cleaned in RESERVED_WIKI_FILES:
        raise ValueError("Writer attempted to touch reserved file")
    if not cleaned.endswith(".md"):
        cleaned += ".md"
    if cleaned == "overview.md":
        return cleaned
    root = cleaned.split("/", 1)[0]
    if root not in ALLOWED_ROOTS:
        raise ValueError(f"Writer path outside allowed wiki roots: {cleaned}")
    return cleaned


def _parse_writeset(text: str) -> list[dict[str, str]]:
    payload = text.strip()
    match = WRITESET_RE.search(payload)
    if match:
        payload = match.group(1)
    parsed = json.loads(payload)
    writes = parsed.get("writes", [])
    if not isinstance(writes, list):
        return []
    normalized: list[dict[str, str]] = []
    for item in writes:
        if not isinstance(item, dict):
            continue
        path = str(item.get("path", "")).strip()
        content = str(item.get("content", "")).strip()
        if not path or not content:
            continue
        normalized.append({"path": path, "content": content})
    return normalized


def _build_writer_prompt(operation: str, source: KnowledgeSource | None, source_text: str, candidate_pages: list[KnowledgePage]) -> str:
    candidates = [
        {
            "path": page.path,
            "type": page.page_type,
            "title": page.title,
            "summary": page.summary,
            "tags": page.tags,
            "aliases": page.aliases,
        }
        for page in candidate_pages
    ]
    source_payload = source.model_dump() if source else None
    return (
        "Produce a JSON object with a single key `writes`.\n"
        "Each item in `writes` must include:\n"
        "- `path`: relative markdown path under wiki/ (examples: entities/foo.md, concepts/bar.md, analyses/baz.md)\n"
        "- `content`: full markdown file content including YAML frontmatter.\n"
        "Never include wiki/index.md or wiki/log.md.\n"
        "Use Obsidian wikilinks in bodies when relevant.\n\n"
        f"Operation: {operation}\n"
        f"Source: {json.dumps(source_payload, ensure_ascii=True)}\n"
        f"Candidate pages: {json.dumps(candidates, ensure_ascii=True)}\n"
        "Source text (truncated):\n"
        f"{source_text[:12000]}"
    )


def _call_writer_model(operation: str, source: KnowledgeSource | None, source_text: str, candidate_pages: list[KnowledgePage]) -> list[dict[str, str]]:
    from langchain_core.messages import HumanMessage, SystemMessage

    prompt = _build_writer_prompt(operation, source, source_text, candidate_pages)
    response = get_llm().invoke(
        [
            SystemMessage(
                content=(
                    "You are a strict knowledge-wiki writer. "
                    "Return only JSON. Do not include commentary."
                )
            ),
            HumanMessage(content=prompt),
        ]
    )
    content = getattr(response, "content", "")
    if isinstance(content, list):
        text = "".join(str(item.get("text", "")) if isinstance(item, dict) else str(item) for item in content)
    else:
        text = str(content)
    return _parse_writeset(text)


def _apply_writer_writes(writes: list[dict[str, str]]) -> list[str]:
    touched: list[str] = []
    for item in writes:
        rel = _normalize_write_path(item["path"])
        target = _safe_relative(_wiki_root(), _wiki_root() / rel)
        _atomic_write(target, item["content"].strip() + "\n")
        touched.append(rel)
    return sorted(set(touched))


def _ensure_source_page(source: KnowledgeSource) -> str:
    rel = f"sources/{_sanitize_slug(source.source_id)}.md"
    target = _wiki_root() / rel
    _atomic_write(target, _source_page_markdown(source))
    return rel


def ingest_note(note_id: str) -> KnowledgeIngestResult:
    ensure_vault_initialized()
    with _operation_lock:
        source, source_text = _snapshot_note(note_id)
        source_page = _ensure_source_page(source)
        candidates = search_pages(query=f"{source.title} {source_text[:500]}", limit=8)
        writes = _call_writer_model("ingest_note", source, source_text, candidates)
        touched = _apply_writer_writes(writes)
        touched.append(source_page)
        rebuild_index()
        log_entry = append_log("ingest_note", f"note:{note_id} source:{source.source_id}")
        return KnowledgeIngestResult(
            operation="ingest_note",
            source=source,
            touched_pages=sorted(set(touched)),
            log_entry=log_entry,
        )


def ingest_file(filename: str, data: bytes) -> KnowledgeIngestResult:
    ensure_vault_initialized()
    with _operation_lock:
        source, source_text = ingest_file_bytes(filename=filename, data=data)
        source_page = _ensure_source_page(source)
        candidates = search_pages(query=f"{source.title} {source_text[:500]}", limit=8)
        writes = _call_writer_model("ingest_file", source, source_text, candidates)
        touched = _apply_writer_writes(writes)
        touched.append(source_page)
        rebuild_index()
        log_entry = append_log("ingest_file", f"file:{filename} source:{source.source_id}")
        return KnowledgeIngestResult(
            operation="ingest_file",
            source=source,
            touched_pages=sorted(set(touched)),
            log_entry=log_entry,
        )


def lint_knowledge_base() -> KnowledgeIngestResult:
    ensure_vault_initialized()
    with _operation_lock:
        index_text = _index_text()
        log_text = _log_path().read_text(encoding="utf-8")
        candidates = list_pages()[:50]
        context = f"Index:\n{index_text}\n\nRecent log:\n{log_text[-8000:]}"
        writes = _call_writer_model("lint", None, context, candidates)
        touched = _apply_writer_writes(writes)
        rebuild_index()
        log_entry = append_log("lint", f"pages:{len(touched)}")
        return KnowledgeIngestResult(
            operation="lint",
            source=None,
            touched_pages=touched,
            log_entry=log_entry,
        )
